name: Test out jq in a pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install git.portable --no-progress --version=2.40.1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.304
      - uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: 1.6
      - name: Run a multi-line script
        run: |
          C:\tools\git\bin\bash.exe --version
          dotnet new console
          echo 'Console.WriteLine("{ \"Hello World\": [1, 2, 3] }");' > Program.cs
          echo 'echo starting; dotnet run | jq; echo done' > test.sh
          C:\tools\git\bin\bash.exe test.sh
