name: Test out jq in a pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-dotnet@v3
      - uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: 1.6
      - name: Run a multi-line script
        shell: bash
        run: |
          dotnet new console
          echo 'Console.WriteLine("{ \"Hello World\": [1, 2, 3] }");' > Program.cs
          echo starting
          dotnet run | jq
          echo done
